name: Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [pr-input]

jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Cypress Tests
        run: |
          echo "E2E Tests Complete"
          sleep 5s

  use_pull_request_number:
    needs: process_input
    runs-on: ubuntu-latest
    steps:
      - name: Use Pull Request Number
        run: |
          echo "Pull Request Number: ${{ github.event.client_payload.prNumber }}"
          echo "Base URL: www.example.com/pr-${{ github.event.client_payload.prNumber }}"
