name: Deploy
on:
  workflow_dispatch:
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Cypress Tests
        run: |
          echo "E2E Tests Complete"
          sleep 10s
